version: "3"
services:
  backend:
    build: app/.
    command: sh -c "alembic upgrade head && uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code


  database:
    image: postgres:15.3-bookworm
    container_name: web-provider-postgres_db
    ports:
      - "5432:5432"
    env_file:
        - .env.db
